// Mocks generated by Mockito 5.4.6 from annotations
// in linglong_store/test/mocks/mock_classes.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:linglong_store/core/network/api_client.dart' as _i16;
import 'package:linglong_store/core/storage/cache_service.dart' as _i18;
import 'package:linglong_store/core/storage/preferences_service.dart' as _i17;
import 'package:linglong_store/data/datasources/remote/app_api_service.dart'
    as _i19;
import 'package:linglong_store/data/models/api_dto.dart' as _i20;
import 'package:linglong_store/data/models/error_solution_dto.dart' as _i21;
import 'package:linglong_store/domain/models/app_comment.dart' as _i9;
import 'package:linglong_store/domain/models/app_detail.dart' as _i7;
import 'package:linglong_store/domain/models/app_version.dart' as _i10;
import 'package:linglong_store/domain/models/install_progress.dart' as _i13;
import 'package:linglong_store/domain/models/install_task.dart' as _i14;
import 'package:linglong_store/domain/models/installed_app.dart' as _i6;
import 'package:linglong_store/domain/models/linglong_cli_failure.dart' as _i2;
import 'package:linglong_store/domain/models/running_app.dart' as _i12;
import 'package:linglong_store/domain/repositories/analytics_repository.dart'
    as _i15;
import 'package:linglong_store/domain/repositories/app_repository.dart' as _i4;
import 'package:linglong_store/domain/repositories/linglong_cli_repository.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:retrofit/retrofit.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDesktopShortcutResult_0 extends _i1.SmartFake
    implements _i2.DesktopShortcutResult {
  _FakeDesktopShortcutResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpResponse_1<T> extends _i1.SmartFake
    implements _i3.HttpResponse<T> {
  _FakeHttpResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppRepository extends _i1.Mock implements _i4.AppRepository {
  MockAppRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.InstalledApp>> getRecommendApps({
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecommendApps, [], {
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i5.Future<List<_i6.InstalledApp>>.value(
              <_i6.InstalledApp>[],
            ),
          )
          as _i5.Future<List<_i6.InstalledApp>>);

  @override
  _i5.Future<List<_i6.InstalledApp>> getAllApps({
    int? page = 1,
    int? pageSize = 20,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllApps, [], {
              #page: page,
              #pageSize: pageSize,
              #category: category,
            }),
            returnValue: _i5.Future<List<_i6.InstalledApp>>.value(
              <_i6.InstalledApp>[],
            ),
          )
          as _i5.Future<List<_i6.InstalledApp>>);

  @override
  _i5.Future<List<_i6.InstalledApp>> searchApps(
    String? keyword, {
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchApps,
              [keyword],
              {#page: page, #pageSize: pageSize},
            ),
            returnValue: _i5.Future<List<_i6.InstalledApp>>.value(
              <_i6.InstalledApp>[],
            ),
          )
          as _i5.Future<List<_i6.InstalledApp>>);

  @override
  _i5.Future<_i7.AppDetail> getAppDetail(
    String? appId, {
    String? arch,
    String? repoName,
    String? module,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAppDetail,
              [appId],
              {#arch: arch, #repoName: repoName, #module: module},
            ),
            returnValue: _i5.Future<_i7.AppDetail>.value(
              _i8.dummyValue<_i7.AppDetail>(
                this,
                Invocation.method(
                  #getAppDetail,
                  [appId],
                  {#arch: arch, #repoName: repoName, #module: module},
                ),
              ),
            ),
          )
          as _i5.Future<_i7.AppDetail>);

  @override
  _i5.Future<List<_i9.AppComment>> getAppComments(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#getAppComments, [appId]),
            returnValue: _i5.Future<List<_i9.AppComment>>.value(
              <_i9.AppComment>[],
            ),
          )
          as _i5.Future<List<_i9.AppComment>>);

  @override
  _i5.Future<bool> saveAppComment({
    required String? appId,
    required String? remark,
    String? version,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveAppComment, [], {
              #appId: appId,
              #remark: remark,
              #version: version,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i10.AppVersion>> getVersions(
    String? appId, {
    String? repoName,
    String? arch,
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getVersions,
              [appId],
              {
                #repoName: repoName,
                #arch: arch,
                #page: page,
                #pageSize: pageSize,
              },
            ),
            returnValue: _i5.Future<List<_i10.AppVersion>>.value(
              <_i10.AppVersion>[],
            ),
          )
          as _i5.Future<List<_i10.AppVersion>>);

  @override
  _i5.Future<List<_i6.InstalledApp>> getRanking({
    String? type = 'new',
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRanking, [], {#type: type, #limit: limit}),
            returnValue: _i5.Future<List<_i6.InstalledApp>>.value(
              <_i6.InstalledApp>[],
            ),
          )
          as _i5.Future<List<_i6.InstalledApp>>);

  @override
  _i5.Future<List<_i6.InstalledApp>> enrichInstalledAppsWithDetails(
    List<_i6.InstalledApp>? apps,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#enrichInstalledAppsWithDetails, [apps]),
            returnValue: _i5.Future<List<_i6.InstalledApp>>.value(
              <_i6.InstalledApp>[],
            ),
          )
          as _i5.Future<List<_i6.InstalledApp>>);

  @override
  _i5.Future<List<_i7.AppDetail>> checkAppUpdates(
    List<_i6.InstalledApp>? apps,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkAppUpdates, [apps]),
            returnValue: _i5.Future<List<_i7.AppDetail>>.value(
              <_i7.AppDetail>[],
            ),
          )
          as _i5.Future<List<_i7.AppDetail>>);
}

/// A class which mocks [LinglongCliRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinglongCliRepository extends _i1.Mock
    implements _i11.LinglongCliRepository {
  MockLinglongCliRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.InstalledApp>> getInstalledApps({
    bool? includeBaseService = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getInstalledApps, [], {
              #includeBaseService: includeBaseService,
            }),
            returnValue: _i5.Future<List<_i6.InstalledApp>>.value(
              <_i6.InstalledApp>[],
            ),
          )
          as _i5.Future<List<_i6.InstalledApp>>);

  @override
  _i5.Future<List<_i12.RunningApp>> getRunningApps() =>
      (super.noSuchMethod(
            Invocation.method(#getRunningApps, []),
            returnValue: _i5.Future<List<_i12.RunningApp>>.value(
              <_i12.RunningApp>[],
            ),
          )
          as _i5.Future<List<_i12.RunningApp>>);

  @override
  _i5.Stream<_i13.InstallProgress> installApp(
    String? appId, {
    String? version,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #installApp,
              [appId],
              {#version: version, #force: force},
            ),
            returnValue: _i5.Stream<_i13.InstallProgress>.empty(),
          )
          as _i5.Stream<_i13.InstallProgress>);

  @override
  _i5.Stream<_i13.InstallProgress> updateApp(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#updateApp, [appId]),
            returnValue: _i5.Stream<_i13.InstallProgress>.empty(),
          )
          as _i5.Stream<_i13.InstallProgress>);

  @override
  _i5.Future<bool> cancelOperation(
    String? appId, {
    required _i14.InstallTaskKind? kind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cancelOperation, [appId], {#kind: kind}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> uninstallApp(String? appId, String? version) =>
      (super.noSuchMethod(
            Invocation.method(#uninstallApp, [appId, version]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> runApp(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#runApp, [appId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> killApp(String? appName) =>
      (super.noSuchMethod(
            Invocation.method(#killApp, [appName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.DesktopShortcutResult> createDesktopShortcut(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#createDesktopShortcut, [appId]),
            returnValue: _i5.Future<_i2.DesktopShortcutResult>.value(
              _FakeDesktopShortcutResult_0(
                this,
                Invocation.method(#createDesktopShortcut, [appId]),
              ),
            ),
          )
          as _i5.Future<_i2.DesktopShortcutResult>);

  @override
  _i5.Future<List<_i6.InstalledApp>> searchVersions(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#searchVersions, [appId]),
            returnValue: _i5.Future<List<_i6.InstalledApp>>.value(
              <_i6.InstalledApp>[],
            ),
          )
          as _i5.Future<List<_i6.InstalledApp>>);

  @override
  _i5.Future<void> pruneApps() =>
      (super.noSuchMethod(
            Invocation.method(#pruneApps, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> getLlCliVersion() =>
      (super.noSuchMethod(
            Invocation.method(#getLlCliVersion, []),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getLlCliVersion, []),
              ),
            ),
          )
          as _i5.Future<String>);
}

/// A class which mocks [AnalyticsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsRepository extends _i1.Mock
    implements _i15.AnalyticsRepository {
  MockAnalyticsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initializeSession() =>
      (super.noSuchMethod(
            Invocation.method(#initializeSession, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> reportVisit({
    String? arch,
    String? llVersion,
    String? llBinVersion,
    String? detailMsg,
    String? osVersion,
    String? repoName,
    String? appVersion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reportVisit, [], {
              #arch: arch,
              #llVersion: llVersion,
              #llBinVersion: llBinVersion,
              #detailMsg: detailMsg,
              #osVersion: osVersion,
              #repoName: repoName,
              #appVersion: appVersion,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> reportInstall(
    String? appId,
    String? version, {
    String? appName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #reportInstall,
              [appId, version],
              {#appName: appName},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> reportUninstall(
    String? appId,
    String? version, {
    String? appName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #reportUninstall,
              [appId, version],
              {#appName: appName},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i16.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [PreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesService extends _i1.Mock
    implements _i17.PreferencesService {
  MockPreferencesService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [CacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheService extends _i1.Mock implements _i18.CacheService {
  MockCacheService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [AppApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppApiService extends _i1.Mock implements _i19.AppApiService {
  MockAppApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.HttpResponse<_i20.CategoryListResponse>>
  getDisCategoryList() =>
      (super.noSuchMethod(
            Invocation.method(#getDisCategoryList, []),
            returnValue:
                _i5.Future<_i3.HttpResponse<_i20.CategoryListResponse>>.value(
                  _FakeHttpResponse_1<_i20.CategoryListResponse>(
                    this,
                    Invocation.method(#getDisCategoryList, []),
                  ),
                ),
          )
          as _i5.Future<_i3.HttpResponse<_i20.CategoryListResponse>>);

  @override
  _i5.Future<_i3.HttpResponse<_i20.AppListResponse>> getSearchAppList(
    _i20.SearchAppListRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSearchAppList, [request]),
            returnValue:
                _i5.Future<_i3.HttpResponse<_i20.AppListResponse>>.value(
                  _FakeHttpResponse_1<_i20.AppListResponse>(
                    this,
                    Invocation.method(#getSearchAppList, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.HttpResponse<_i20.AppListResponse>>);

  @override
  _i5.Future<_i3.HttpResponse<_i20.AppListArrayResponse>> getAppDetails(
    List<_i20.AppDetailsBO>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAppDetails, [body]),
            returnValue:
                _i5.Future<_i3.HttpResponse<_i20.AppListArrayResponse>>.value(
                  _FakeHttpResponse_1<_i20.AppListArrayResponse>(
                    this,
                    Invocation.method(#getAppDetails, [body]),
                  ),
                ),
          )
          as _i5.Future<_i3.HttpResponse<_i20.AppListArrayResponse>>);

  @override
  _i5.Future<_i3.HttpResponse<_i20.AppDetailResponse>> getAppDetail(
    List<_i20.AppDetailSearchBO>? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAppDetail, [request]),
            returnValue:
                _i5.Future<_i3.HttpResponse<_i20.AppDetailResponse>>.value(
                  _FakeHttpResponse_1<_i20.AppDetailResponse>(
                    this,
                    Invocation.method(#getAppDetail, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.HttpResponse<_i20.AppDetailResponse>>);

  @override
  _i5.Future<_i3.HttpResponse<_i20.AppCommentListResponse>> getAppCommentList(
    _i20.AppCommentSearchBO? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAppCommentList, [request]),
            returnValue:
                _i5.Future<_i3.HttpResponse<_i20.AppCommentListResponse>>.value(
                  _FakeHttpResponse_1<_i20.AppCommentListResponse>(
                    this,
                    Invocation.method(#getAppCommentList, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.HttpResponse<_i20.AppCommentListResponse>>);

  @override
  _i5.Future<_i3.HttpResponse<_i20.BooleanResponse>> saveAppComment(
    _i20.AppCommentSaveBO? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveAppComment, [request]),
            returnValue:
                _i5.Future<_i3.HttpResponse<_i20.BooleanResponse>>.value(
                  _FakeHttpResponse_1<_i20.BooleanResponse>(
                    this,
                    Invocation.method(#saveAppComment, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.HttpResponse<_i20.BooleanResponse>>);

  @override
  _i5.Future<_i3.HttpResponse<_i20.StringResponse>> findShellString() =>
      (super.noSuchMethod(
            Invocation.method(#findShellString, []),
            returnValue:
                _i5.Future<_i3.HttpResponse<_i20.StringResponse>>.value(
                  _FakeHttpResponse_1<_i20.StringResponse>(
                    this,
                    Invocation.method(#findShellString, []),
                  ),
                ),
          )
          as _i5.Future<_i3.HttpResponse<_i20.StringResponse>>);

  @override
  _i5.Future<_i3.HttpResponse<_i21.ErrorSolutionResponse>> findErrorSolution(
    String? visitorId,
    _i21.ErrorSolutionFindRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findErrorSolution, [visitorId, request]),
            returnValue:
                _i5.Future<_i3.HttpResponse<_i21.ErrorSolutionResponse>>.value(
                  _FakeHttpResponse_1<_i21.ErrorSolutionResponse>(
                    this,
                    Invocation.method(#findErrorSolution, [visitorId, request]),
                  ),
                ),
          )
          as _i5.Future<_i3.HttpResponse<_i21.ErrorSolutionResponse>>);

  @override
  _i5.Future<_i3.HttpResponse<_i20.AppListArrayResponse>>
  getWelcomeCarouselList(_i20.AppWelcomeSearchRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#getWelcomeCarouselList, [request]),
            returnValue:
                _i5.Future<_i3.HttpResponse<_i20.AppListArrayResponse>>.value(
                  _FakeHttpResponse_1<_i20.AppListArrayResponse>(
                    this,
                    Invocation.method(#getWelcomeCarouselList, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.HttpResponse<_i20.AppListArrayResponse>>);

  @override
  _i5.Future<_i3.HttpResponse<_i20.AppListResponse>> getWelcomeAppList(
    _i20.PageParams? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWelcomeAppList, [request]),
            returnValue:
                _i5.Future<_i3.HttpResponse<_i20.AppListResponse>>.value(
                  _FakeHttpResponse_1<_i20.AppListResponse>(
                    this,
                    Invocation.method(#getWelcomeAppList, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.HttpResponse<_i20.AppListResponse>>);

  @override
  _i5.Future<_i3.HttpResponse<_i20.AppDetailListResponse>> appCheckUpdate(
    List<_i20.AppCheckVersionBO>? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#appCheckUpdate, [request]),
            returnValue:
                _i5.Future<_i3.HttpResponse<_i20.AppDetailListResponse>>.value(
                  _FakeHttpResponse_1<_i20.AppDetailListResponse>(
                    this,
                    Invocation.method(#appCheckUpdate, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.HttpResponse<_i20.AppDetailListResponse>>);

  @override
  _i5.Future<_i3.HttpResponse<_i20.AppListResponse>> getNewAppList(
    _i20.PageParams? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNewAppList, [request]),
            returnValue:
                _i5.Future<_i3.HttpResponse<_i20.AppListResponse>>.value(
                  _FakeHttpResponse_1<_i20.AppListResponse>(
                    this,
                    Invocation.method(#getNewAppList, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.HttpResponse<_i20.AppListResponse>>);

  @override
  _i5.Future<_i3.HttpResponse<_i20.AppListResponse>> getInstallAppList(
    _i20.PageParams? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getInstallAppList, [request]),
            returnValue:
                _i5.Future<_i3.HttpResponse<_i20.AppListResponse>>.value(
                  _FakeHttpResponse_1<_i20.AppListResponse>(
                    this,
                    Invocation.method(#getInstallAppList, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.HttpResponse<_i20.AppListResponse>>);

  @override
  _i5.Future<_i3.HttpResponse<_i20.VersionListResponse>>
  getSearchAppVersionList(_i20.AppVersionListRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#getSearchAppVersionList, [request]),
            returnValue:
                _i5.Future<_i3.HttpResponse<_i20.VersionListResponse>>.value(
                  _FakeHttpResponse_1<_i20.VersionListResponse>(
                    this,
                    Invocation.method(#getSearchAppVersionList, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.HttpResponse<_i20.VersionListResponse>>);

  @override
  _i5.Future<_i3.HttpResponse<_i20.SidebarConfigResponse>> getSidebarConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getSidebarConfig, []),
            returnValue:
                _i5.Future<_i3.HttpResponse<_i20.SidebarConfigResponse>>.value(
                  _FakeHttpResponse_1<_i20.SidebarConfigResponse>(
                    this,
                    Invocation.method(#getSidebarConfig, []),
                  ),
                ),
          )
          as _i5.Future<_i3.HttpResponse<_i20.SidebarConfigResponse>>);

  @override
  _i5.Future<_i3.HttpResponse<_i20.AppListResponse>> getSidebarApps(
    _i20.SidebarAppsRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSidebarApps, [request]),
            returnValue:
                _i5.Future<_i3.HttpResponse<_i20.AppListResponse>>.value(
                  _FakeHttpResponse_1<_i20.AppListResponse>(
                    this,
                    Invocation.method(#getSidebarApps, [request]),
                  ),
                ),
          )
          as _i5.Future<_i3.HttpResponse<_i20.AppListResponse>>);

  @override
  _i5.Future<_i3.HttpResponse<dynamic>> saveVisitRecord(
    _i20.SaveVisitRecordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveVisitRecord, [request]),
            returnValue: _i5.Future<_i3.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_1<dynamic>(
                this,
                Invocation.method(#saveVisitRecord, [request]),
              ),
            ),
          )
          as _i5.Future<_i3.HttpResponse<dynamic>>);

  @override
  _i5.Future<_i3.HttpResponse<dynamic>> saveInstalledRecord(
    _i20.SaveInstalledRecordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveInstalledRecord, [request]),
            returnValue: _i5.Future<_i3.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_1<dynamic>(
                this,
                Invocation.method(#saveInstalledRecord, [request]),
              ),
            ),
          )
          as _i5.Future<_i3.HttpResponse<dynamic>>);
}
